#! /bin/bash

echo

# install poetry
curl -sSL https://install.python-poetry.org | python3 -

echo
echo "------------------------------------------------------------------------"
echo

# create virtual environment
"$HOME/.local/bin/poetry" env use python3
"$HOME/.local/bin/poetry" env info

echo
echo "------------------------------------------------------------------------"
echo

# install dependencies
"$HOME/.local/bin/poetry" install --with dev --sync
echo
