#! /bin/bash

echo

# install poetry
curl -sSL https://install.python-poetry.org | python3 -

echo
echo "------------------------------------------------------------------------"
echo

# create virtual environment
poetry env use python3
poetry env info

echo
echo "------------------------------------------------------------------------"
echo

# install dependencies
poetry install --with dev --sync
echo
