#! /bin/bash

echo

if [ ! -d "./.venv" ]; then
    echo "  Environment has not yet been set up."
    echo "  Please call \"./script/bootstrap\" first."
    echo
    exit 1
fi


echo "  Nothing to do."
echo "  Let's do something, I'm bored."

./process_templates.sh
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    exit $EXIT_CODE
fi

echo "  Wasn't that fun?"
echo "  Done."
echo

exit 0
