#! /bin/bash

echo
uv tree --no-dev
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
   echo
   exit $EXIT_CODE
fi

echo
echo "------------------------------------------------------------------------"
echo

uv tree --only-dev
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
   echo
   exit $EXIT_CODE
fi

echo
